language: r

cache:
  - packages
  - ccache

sudo: required
dist: trusty
latex: false

r:
  - release

before_install:
  - sudo apt-get update
  - sudo apt-get install -y software-properties-common
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos-dev libgdal-dev liblwgeom-2.4-0

env:
   global:
     - R_BUILD_ARGS="--no-vignettes --no-manual"
     - R_CHECK_ARGS="--no-vignettes --no-manual --as-cran"
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false
     - R_CODECOV=true

warnings_are_errors: false

r_github_packages:
  - jimhester/covr
  - r-spatial/lwgeom

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
