language: r
cache:
  - packages
  - ccache
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      r: devel
      env: R_CODECOV=true
#    - os: linux
#      r: release

#addons:
#  apt:
#    sources:
#      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
#    packages:
#      - libudunits2-dev
#      - libproj-dev
#      - libgeos-dev
#      - libgdal-dev
#      - liblwgeom-dev

addons:
  postgresql: "9.6"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  # sf dependencies:
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  # postgis/liblwgeom source compile dependencies:
  - sudo apt-get --yes install libjson-c-dev postgresql-server-dev-9.6
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  - sudo ldconfig

env:
   global:
     - R_BUILD_ARGS="--no-vignettes --no-manual"
     - R_CHECK_ARGS="--no-vignettes --no-manual --as-cran"
     - NOT_CRAN="true"
     - _R_CHECK_FORCE_SUGGESTS_=false

warnings_are_errors: true

#script:
#  - |
#    R CMD build .
#    travis_wait 20 R CMD check nhdplusTools*tar.gz

r_github_packages:
  - jimhester/covr

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
